### ISSUE TITLE
Added Tailwind

### ISSUE THREAD

**Issue by 0xf17** [mathslab-srishti/explain-with-gif#4]
Added related dependencies and setup tailwind for direct use in templates/html.

Ignore `_sass` folder for now. To create/edit css, use `assets/css/main.scss`, Jekyll will compile it into `assets/css/main.css` automatically. I believe this will be phased out after we replace existing classes with Tailwind utility classes.

This issue was created only for the updating this information. Will be closed in next 24 hours.

cc: @thedivtagguy

**Comment by 0xf17** [comment]
Run `bundle install` to update gem dependencies i.e. `jekyll-postcss`, and then relevant npm installs.

**Comment by thedivtagguy** [comment]
Oh wow!
This makes things a whole lot easier. I'm not familiar with installing Tailwind manually, I tend to use a boilerplate. Thanks so much, I'll give this a run :)
